name: E2E • Electron • Cucumber

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    env:
      CI: true
      ELECTRON_ENABLE_LOGGING: 1
      # Set if your tests look for this to decide "headed" mode
      HEADED: 1
      # Optional: where your app entry lives if needed by your steps
      APP_ENTRY: app/main.js

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # If you use Playwright APIs *at all* (even for Electron),
      # this ensures runner deps are present.
      - name: Install Playwright system deps
        run: npx playwright install --with-deps

      # Optional: if your tests produce cucumber JSON/HTML or Playwright traces
      - name: Prepare reports dir
        run: mkdir -p ./reports ./playwright-traces

      # Run Cucumber under xvfb so Electron has a display
      - name: Run Cucumber tests (Electron)
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1440x900x24" \
            npx cucumber-js \
              --publish-quiet \
              --format @cucumber/pretty-formatter \
              --format json:reports/cucumber.json
        # ^ adjust args/formatters to your project (e.g. --require-module ts-node/register, --require tests/steps/**/*.ts)

      # If you generate Playwright traces on failure, upload them
      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: playwright-traces
          if-no-files-found: ignore
          retention-days: 7

      # Upload cucumber reports
      - name: Upload Cucumber report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: reports
          if-no-files-found: ignore
          retention-days: 7
